import { Component, ViewChild } from '@angular/core';
import { MatPaginator, PageEvent } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { ApiserviceService } from 'src/app/services/apiservice.service';
import { GetdataService } from 'src/app/services/getdata.service';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.scss']
})
export class UserListComponent {
  dataSource!: MatTableDataSource<any>;
  displayedColumns: string[] = [
    "companyId",
    "DomainName",
    "Name",
    "PlanName",
    "PlanPrice",
    "NoofHits",
    "LastLogin",
    "Email",
    "Company",
    "Country",
    "CreatedDate",
    "StartedDate",
    "AC_Type",
    "Status",
    "Action"
  ]

  userArray = [
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasiainfotech",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },
    {
      companyId: "compIdOne",
      DomainName: 'abc.com',
      Name: "xyz",
      PlanName: 'starter',
      PlanPrice: '$200',
      NoofHits: '4',
      LastLogin: '19/05/2023',
      Email: "xyz@gmail.com",
      Company: "seasia pvt.ltd",
      Country: 'india',
      CreatedDate: '19/05/2023',
      StartedDate: '21/05/2023',
      AC_Type: "cash",
      Status: "Active",
      Action: ["view", "edit", "Delete"]
    },

  ]

  @ViewChild(MatPaginator, { static: true }) paginator!: MatPaginator;
  pageSize = 10;
  pageIndex = 0;
  totalItems!: number;
  searchTerm: any;

  constructor(private dataservice: GetdataService,
    private apiService: ApiserviceService,
    private router: Router
  ) { }


  ngOnInit() {
    this.loadTableData()
    this.getUserDetails();
  }

  onColumClick() {

  }

  navigateTo(event: Event) {
    const route = (event.target as HTMLSelectElement).value;
    let baseUrl = '/home/users/';
    let url: string = '';
    if (route) {
      if (route === 'view-user' || route === 'edit-user' || route === 'upgrade-plan') {
        const queryId = 1256;
        url = `${baseUrl}${route}?id=${queryId}`;
        this.router.navigateByUrl(url);
      }
      else {
        if (route === 'gotoSite') {
          url = 'https://realstate.appsndevs.com';
          window.location.href = url
        }
        else if (route === 'mail') {
          console.log('mail api will be send');
        }
        else{
          console.log('deactivate user works')
        }
      }
    }
  }

  loadTableData() {
    this.dataservice.getData(this.pageIndex, this.pageSize).subscribe((data: any) => {
      this.dataSource = new MatTableDataSource(this.userArray);
      console.log(this.dataSource, "datasource")
      this.totalItems = data.length;
      this.dataSource.paginator = this.paginator;
      console.log(data, "data");
      console.log(this.totalItems, "totalItems")
      // this.applyFilter()
    })
  }

  getUserDetails() {
    let url = '/Companies/List/jqgrid'

    this.apiService.getUserData(url).subscribe((res) => {
      console.log(res, "ressssssss")
    }, ((err) => {
      console.log(err, "errrrrrrrrrr")
    }))
  }


  onPageChange(event: PageEvent): void {
    // Update the pagination properties
    this.pageSize = event.pageSize;
    this.pageIndex = event.pageIndex;

    // Fetch data from the API based on the updated pagination properties
    this.loadTableData();
  }

  applyFilter(): void {
    // Convert the search term to lowercase
    const filterValue = this.searchTerm.toLowerCase();

    // Apply the filter to the data source
    this.dataSource.filter = filterValue.trim().toLowerCase();
  }




  userHeadElements = [
    "Company Id",
    "Domain Name",
    "Name",
    "Plan Name",
    "Plan Price",
    "No of Hits",
    "Last Login",
    "Email",
    "Company",
    "Country",
    "company",
    "Country",
    "Created Date",
    "Started Date",
    "A/C Type",
    "Status",
    "Action"
  ]



}
